#!/usr/bin/env bash
#  Bash script that gives you information about the holbertonschool file.
if test -f school 
then echo "file exists."
else echo "file does not exist"
fi
if test -s school
then echo "school file is not empty"
else echo "school file is empty" 
fi
if test -f school
then echo "school is a regular file"
fi