#!/usr/bin/env bash
#  Bash script that gives you information about the holbertonschool file.
if test -f school 
then echo "school file exists"
else echo "school file does not exist"
     exit 1 
fi
if test -s school
then echo "school file is not empty"
else echo "school file is empty" 
fi
if test -f school
then echo "school is a regular file"
fi