#!/bin/bash

# This script reloads Gunicorn gracefully without downtime

# Find the master Gunicorn process ID
GUNICORN_PID=$(ps aux | grep '[g]unicorn' | awk '{print $2}')

if [ -z "$GUNICORN_PID" ]; then
  echo "Gunicorn master process not found"
  exit 1
fi

# Send the SIGHUP signal to the Gunicorn master process
kill -HUP $GUNICORN_PID

if [ $? -eq 0 ]; then
  echo "Gunicorn master process with PID $GUNICORN_PID has been reloaded"
else
  echo "Failed to reload Gunicorn master process"
fi
